[project]
name = "pychisel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "paramiko>=4.0.0",
    "uvloop>=0.22.1",
    "websocket-client>=1.9.0",
    "websockets>=16.0",
]
